"""empty message

Revision ID: 17d37674dae0
Revises: None
Create Date: 2016-10-31 16:46:02.620283

"""

# revision identifiers, used by Alembic.
revision = '17d37674dae0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import Text
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###
